version: '3.7'

services:
  zoo:
    image: zookeeper
    hostname: zoo
    restart: always
    ports:
      - 2181:2181
  kafka:
    image: confluentinc/cp-kafka
    hostname: kafka
    depends_on:
      - zoo
    ports:
      - 9092:9092
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zoo:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1